TEMP_DIR := ../../temp
CROSS := 960
GCC := gcc
LINKTOOL  := gld
GCC_ARGS := -crt -nostdinc -nostdlib -verbose-asm -v -Felf

all:
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/action.s -o action/action.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_1344C.s -o action/act_1344C.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_13464.s -o action/act_13464.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_1346C.s -o action/act_1346C.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_134A8.s -o action/act_134A8.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_motion.s -o action/act_rc_motion.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_kaeshi.s -o action/act_rc_kaeshi.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_syagami.s -o action/act_rc_syagami.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_walk.s -o action/act_rc_walk.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_bwalk.s -o action/act_rc_bwalk.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_fumikomi.s -o action/act_rc_fumikomi.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_run.s -o action/act_rc_run.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_ta_guard.s -o action/act_rc_ta_guard.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_guard.s -o action/act_rc_guard.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_yarare.s -o action/act_rc_yarare.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_down_attack.s -o action/act_rc_down_attack.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_jump.s -o action/act_rc_jump.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_ukemi.s -o action/act_rc_ukemi.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_down.s -o action/act_rc_down.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_rise.s -o action/act_rc_rise.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_kawashi.s -o action/act_rc_kawashi.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_down_nage_touch.s -o action/act_rc_down_nage_touch.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_nage_touch.s -o action/act_rc_nage_touch.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_nage.s -o action/act_rc_nage.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_nagerare.s -o action/act_rc_nagerare.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_kabe_nage.s -o action/act_rc_kabe_nage.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_1560C.s -o action/act_1560C.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_156EC.s -o action/act_156EC.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_159B0.s -o action/act_159B0.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_15A4C.s -o action/act_15A4C.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_15C48.s -o action/act_15C48.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_15DFC.s -o action/act_15DFC.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_15EE8.s -o action/act_15EE8.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_16120.s -o action/act_16120.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_rc_kabehit.s -o action/act_rc_kabehit.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_163A0.s -o action/act_163A0.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_164DC.s -o action/act_164DC.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_16594.s -o action/act_16594.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_165D4.s -o action/act_165D4.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_168DC.s -o action/act_168DC.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/act_16A4C.s -o action/act_16A4C.o
	
	$(GCC)$(CROSS) -r $(GCC_ARGS) camera/rob_disp.s -o camera/rob_disp.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) option/option.s -o option/option.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/set_motion.s -o action/set_motion.o
	$(GCC)$(CROSS) -r $(GCC_ARGS) action/play_motion.s -o action/play_motion.o